builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/gapp
    goos:
      - windows
      - darwin
      - linux
    ldflags:
      - -X github.com/eikc/gapp/internal/cli.Build={{ .ShortCommit }}
      - -X github.com/eikc/gapp/internal/cli.Major={{ .Major }}
      - -X github.com/eikc/gapp/internal/cli.Minor={{ .Minor }}
      - -X github.com/eikc/gapp/internal/cli.Patch={{ .Patch }}
      - -X github.com/eikc/gapp/internal/cli.Label=release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: eikc
    name: gapp

brews:
  - name: gapp
    github:
      owner: eikc
      name: gapp-homebrew-tap
    folder: Formula
    description: Small utility cli to ease the use of github
    test: |
      system "gapp version"
